### ISSUE TITLE
UnknownHostException trying to hit Amazon Elasticsearch endpoint

### ISSUE THREAD

**Issue by euccastro** [mpenet/spandex#38]
I have an Amazon Elasticsearch domain with endpoint `https://search-semente-mbk7y7yizywtxbov5s64to2gdm.eu-central-1.es.amazonaws.com/`.  I can hit it alright via `curl`:
```
es@bocha:~/src/semente$ curl -i -X GET "https://search-semente-mbk7y7yizywtxbov5s64to2gdm.eu-central-1.es.amazonaws.com/_cat/health?v"
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: text/plain;charset=UTF-8
Content-Length: 310
Connection: keep-alive

epoch      timestamp cluster              status node.total node.data shards pri relo init unassign pending_tasks max_task_wait_time active_shards_percent
1533147464 11:17:44  563900263565:semente yellow          1         1     15  15    0    0       15             0                  -                 50.0%
```

but if i try the same with spandex

```
(require '[qbits.spandex :as sp])

(def c (sp/client {:hosts ["https://search-semente-mbk7y7yizywtxbov5s64to2gdm.eu-central-1.es.amazonaws.com"]}))

(sp/request c {:method :get :url "/_cat/health?v"})
```

then I get the following exception:

```
2. Unhandled java.io.IOException
   search-semente-mbk7y7yizywtxbov5s64to2gdm.eu-central-1.es.amazonaws.com/:
   unknown error

           RestClient.java:  728  org.elasticsearch.client.RestClient$SyncResponseListener/get
           RestClient.java:  235  org.elasticsearch.client.RestClient/performRequest
               spandex.clj:  277  qbits.spandex/request
               spandex.clj:  265  qbits.spandex/request
                      REPL:   51  user/eval25613
                      REPL:   51  user/eval25613
             Compiler.java: 7062  clojure.lang.Compiler/eval
             Compiler.java: 7025  clojure.lang.Compiler/eval
                  core.clj: 3206  clojure.core/eval
                  core.clj: 3202  clojure.core/eval
                  main.clj:  243  clojure.main/repl/read-eval-print/fn
                  main.clj:  243  clojure.main/repl/read-eval-print
                  main.clj:  261  clojure.main/repl/fn
                  main.clj:  261  clojure.main/repl
                  main.clj:  177  clojure.main/repl
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  657  clojure.core/apply
                  core.clj:  652  clojure.core/apply
                regrow.clj:   18  refactor-nrepl.ns.slam.hound.regrow/wrap-clojure-repl/fn
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  657  clojure.core/apply
                  core.clj: 1965  clojure.core/with-bindings*
                  core.clj: 1965  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
    interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                  AFn.java:   22  clojure.lang.AFn/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  745  java.lang.Thread/run

1. Caused by java.net.UnknownHostException
   search-semente-mbk7y7yizywtxbov5s64to2gdm.eu-central-1.es.amazonaws.com/:
   unknown error

     Inet6AddressImpl.java:   -2  java.net.Inet6AddressImpl/lookupAllHostAddr
          InetAddress.java:  928  java.net.InetAddress$2/lookupAllHostAddr
          InetAddress.java: 1323  java.net.InetAddress/getAddressesFromNameService
          InetAddress.java: 1276  java.net.InetAddress/getAllByName0
          InetAddress.java: 1192  java.net.InetAddress/getAllByName
          InetAddress.java: 1126  java.net.InetAddress/getAllByName
SystemDefaultDnsResolver.java:   45  org.apache.http.impl.conn.SystemDefaultDnsResolver/resolve
PoolingNHttpClientConnectionManager.java:  609  org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver/resolveRemoteAddress
PoolingNHttpClientConnectionManager.java:  580  org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver/resolveRemoteAddress
  AbstractNIOConnPool.java:  427  org.apache.http.nio.pool.AbstractNIOConnPool/processPendingRequest
  AbstractNIOConnPool.java:  276  org.apache.http.nio.pool.AbstractNIOConnPool/lease
PoolingNHttpClientConnectionManager.java:  266  org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager/requestConnection
AbstractClientExchangeHandler.java:  363  org.apache.http.impl.nio.client.AbstractClientExchangeHandler/requestConnection
DefaultClientExchangeHandlerImpl.java:  125  org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl/start
InternalHttpAsyncClient.java:  141  org.apache.http.impl.nio.client.InternalHttpAsyncClient/execute
           RestClient.java:  366  org.elasticsearch.client.RestClient/performRequestAsync
           RestClient.java:  351  org.elasticsearch.client.RestClient/performRequestAsyncNoCatch
           RestClient.java:  233  org.elasticsearch.client.RestClient/performRequest
               spandex.clj:  277  qbits.spandex/request
               spandex.clj:  265  qbits.spandex/request
                      REPL:   51  user/eval25613
                      REPL:   51  user/eval25613
             Compiler.java: 7062  clojure.lang.Compiler/eval
             Compiler.java: 7025  clojure.lang.Compiler/eval
                  core.clj: 3206  clojure.core/eval
                  core.clj: 3202  clojure.core/eval
                  main.clj:  243  clojure.main/repl/read-eval-print/fn
                  main.clj:  243  clojure.main/repl/read-eval-print
                  main.clj:  261  clojure.main/repl/fn
                  main.clj:  261  clojure.main/repl
                  main.clj:  177  clojure.main/repl
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  657  clojure.core/apply
                  core.clj:  652  clojure.core/apply
                regrow.clj:   18  refactor-nrepl.ns.slam.hound.regrow/wrap-clojure-repl/fn
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  657  clojure.core/apply
                  core.clj: 1965  clojure.core/with-bindings*
                  core.clj: 1965  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
    interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                  AFn.java:   22  clojure.lang.AFn/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  745  java.lang.Thread/run

```
